question_prompt_template: |
  以下は大学生のプレゼン資料の抜粋です。この内容から、発表を聞いた学生がしそうな質問を{max_questions}個生成してください。
  出力形式はQ1:〜、Q2:〜 のように記載してください。また、想定質問以外の文章は出力しないでください

  --- スライド内容 ---
  {slide_text}
  ---------------------

image_source_prompt_template: |
  この画像は講義のスライドに含まれていた図です。
  この図の出典元（論文名・ウェブサイト名・書籍、サイトリンク）を推測してください。
  また、他の解説や文章は無しで、出典元のみを回答してください。

