question_prompt_template: |
  以下は大学生のプレゼン資料の抜粋です。この内容から、発表を聞いた学生がしそうな質問を{max_questions}個生成してください。
  出力形式はQ1:〜、Q2:〜 のように記載してください。また、想定質問以外の文章は出力しないでください

  --- スライド内容 ---
  {slide_text}
  ---------------------
